### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by chaojiang06** [slei109/CLTP#1]
Hi, thank you for the great work! I am interested in utilizing your work in multilingual NLP research, and it would be awesome if the code can be available. Just want to check in if there is an estimated time for releasing the code.

Thanks again for the great work!

**Comment by slei109** [comment]
Thanks for your interest! Currently, I'm working on cleaning the code up and waiting for the release permission. Hopefully, this won't take too long. I'll let you know when it's ready :)

**Comment by chaojiang06** [comment]
That sounds great! Thank you in advance!

**Comment by slei109** [comment]
> That sounds great! Thank you in advance!

The code for xnli task has been released. Thanks for your interest!
